### ISSUE TITLE
quoted scalars consisting of digits are returned as numbers instead of strings

### ISSUE THREAD

**Issue by smls** [tony-o/perl6-libyaml#1]
```
➜  echo "a: '001'" > a.yml
➜  perl6 -e 'use YAML::Parser::LibYAML:auth<github:tony-o>; dd yaml-parse "a.yml";'
${:a(1)}
```

expected output:

```
${:a("001")}
```

Representing this scalar as an `Int` even though it was quoted in the YAML file, looses information (the leading zeros) and I'm pretty sure it violates against the YAML spec.

**Comment by tony-o** [comment]
This should be fixed in `0.0.5` -
